### ISSUE TITLE
Support hotkeys

### ISSUE THREAD

**Issue by eroshenkoam** [allure-framework/allure2#269]

**Comment by baev** [comment]
The list of hotkeys I'd like to be supported:

- [ ] Go to the next/previous tab
- [ ] Go to the next/previous test case
- [ ] Go to the next/previous failed/broken test case
- [ ] Close last pane
- [ ] Go to the next/previous step
- [ ] Go to the next/previous failed/broken step
- [ ] Go to the next/previous attachment
- [ ] Copy the full name of the current test case
