### ISSUE TITLE
Export tree to csv, pdf

### ISSUE THREAD

**Issue by eroshenkoam** [allure-framework/allure2#273]
- [ ] Summary mail
- [ ] PDF with overall test results
- [ ] CSV with overall test results
- [ ] Badge with statistics ![](https://img.shields.io/badge/tests-2/10-red.svg)

**Comment by gavrilfb** [comment]
Hello, can I ask if exporting as PDF will be implemented in the future?
Although seeing as this issue has been closed when CSV was implemented, I assume it's not possible?

**Comment by abhitechno01** [comment]
Hi, I've been searching for a way to download reports as PDF. Few searches lead me to this issue page.So, is the new feature implemented and can we download reports as PDF ?
If yes, then can you share the documentation of how to download report as pdf.

Thanks in advance

**Comment by marcjohnen** [comment]
So this is released in 2.6? But it does not seem to be documented. From the sourcecode I don't understand how to use it.

**Comment by Deop** [comment]
Hi. Is there any documentation on how to use implemented export functionality?

**Comment by nastya1413** [comment]
Any news related to above @eroshenkoam, @baev?

**Comment by nareshkc** [comment]
Hi.. When can i expect this future test result export to CSV/ excel... if this future already there in previous releases.. please let me know in which version and how can i export result into CSV/excel....Thank you

**Comment by Sup3rGeo** [comment]
For those interested in a simple application to generate a docx (and a pdf file) out of allure results, check this out:

https://github.com/typhoon-hil/allure-docx

**Comment by Sup3rGeo** [comment]
@0107shashankgarg it should be possible although I am not testing frequently. Check the project's page, I just added instructions.

**Comment by gavrilfb** [comment]
Hi @eroshenkoam 

Can we know if currently there are any efforts for PDF exporting feature development?

Thank you.

**Comment by neerukonda9** [comment]
Hi @eroshenkoam 
Can you please share the update with PDF exporting feature dev activity? 

Thanks,

**Comment by Abintv** [comment]
Hi, is it possible to generate custom CSV report including column for screenshot of f failed scenarios with test results using allure ( testing framework :pytest) ?

**Comment by nfvTest** [comment]
hi is there a way generate a pdf allure report
